### PR TITLE
Less laggy gif and something else

### PR DESCRIPTION
**Pull request by Xemply**

### CODE REVIEW

**Comment by Smertig** [comment]
Thanks for PR!
Could you explain why original gif is laggy? On my PC/phone both mine and your gifs look good (without freezes). However, lyrics on your gif are less readable (probably due to fast song speed or smaller font size):

image image


BTW, original animation is `webp`, not a `gif`. Original `gif` was 25 Mb and only 8 Mb after converting to `webp`.

**Comment by Xemply** [comment]
Ok I’ll convert to webp fix graphics and make another pr that’s weird tho because on my device the webp is slow and choppy

**Comment by Smertig** [comment]
If you have any issues with `webp`, we should probably try using something else. However, I don't like `gif`s because of size overhead (for both repo and repo visitors).

Could you also explain what's wrong (or missing) with original `webp` other than its format?

**Comment by Xemply** [comment]
for me it is quite laggy also the gif rick roll is funnier

**Pull request closed without merging**
